version: 0.0
os: linux
files:
 - source: /
   destionation: /home/ec2-user/express-app
hooks: 
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout : 300
      runas : ec2-user
